### ISSUE TITLE
Not really an issue but where and what should be modified to connect on an mqtt server with name and password

### ISSUE THREAD

**Issue by Domos2** [Mickaelh51/rflink2mqtt#1]
Hi, as mentionned I'am trying to use this container to link my rflink; 
My mqtt server is password protected How can I can change the code to match with my data;
I don't know python but I've found where I have to change the port but for the other things I don't know; Could you help me with a modified python script or a clear tutorial about where and what I have to modify;

Take for clear example these data for mqtt:
host: 10.0.0.60 port :8888
user: jean
password : abeautifulpassword

Thanks for help (I'am french if easier for answering)

**Comment by Mickaelh51** [comment]
Hi, I just push a new release with login and password.
in your docker-compose just add

"MQTT_SERVER=10.0.0.60"
"MQTT_PORT=8888"
"MQTT_USERNAME=jean"
"MQTT_PWD=abeautifulpassword"
"USB_INTERFACE=/dev/YOURUSBDEVICE"

please pull a latest docker image version

I can't test right now, can you tell me if is it ok for you ?

thanks

**Comment by Domos2** [comment]
Hi, seems not working or I did wrong... This is my docker compose and after the error log sent by the container:

version: '3.3'

networks:
  omv_network:
    external: true

services:
  rflink2mqtt:
    image: mickaelh51/rflink2mqtt:latest
    container_name: rflink2mqtt
    hostname: rflink2mqtt
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    environment:
      - "MQTT_SERVER=10.0.0.69"
      - "MQTT_PORT=6666"
      - "MQTT_USERNAME=jean"
      - "MQTT_PWD=abeautifulpassword"
      - "USB_INTERFACE=/dev/ttyACM0"
      - "PUID=1000"
      - "PGID=100"
    group_add:
      - dialout
    restart: always
    networks:
      - omv_network



2023-01-30 02:30:07,775 INFO Connected to device:/dev/ttyACM0
Traceback (most recent call last):
  File "/usr/src/app/rflink2mqtt.py", line 183, in <module>
    client.connect(MQTT_SERVER, MQTT_PORT)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 912, in connect
    self.connect_async(host, port, keepalive,
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 979, in connect_async
    if port <= 0:
TypeError: '<=' not supported between instances of 'str' and 'int'
2023-01-30 02:30:11,939 INFO Connected to device:/dev/ttyACM0
Traceback (most recent call last):
  File "/usr/src/app/rflink2mqtt.py", line 183, in <module>
    client.connect(MQTT_SERVER, MQTT_PORT)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 912, in connect
    self.connect_async(host, port, keepalive,
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 979, in connect_async
    if port <= 0:
TypeError: '<=' not supported between instances of 'str' and 'int'

Did I something wrong or there is another issue ? Sorry to disturb you with this...

**Comment by Domos2** [comment]
> Hi, seems not working or I did wrong... This is my docker compose and after the error log sent by the container:
> 
> version: '3.3'
> 
> networks: omv_network: external: true
> 
> services: rflink2mqtt: image: mickaelh51/rflink2mqtt:latest container_name: rflink2mqtt hostname: rflink2mqtt devices: - "/dev/ttyACM0:/dev/ttyACM0" environment: - "MQTT_SERVER=10.0.0.69" - "MQTT_PORT=6666" - "MQTT_USERNAME=jean" - "MQTT_PWD=abeautifulpassword" - "USB_INTERFACE=/dev/ttyACM0" - "PUID=1000" - "PGID=100" group_add: - dialout restart: always networks: - omv_network
> 
> 2023-01-30 02:30:07,775 INFO Connected to device:/dev/ttyACM0 Traceback (most recent call last): File "/usr/src/app/rflink2mqtt.py", line 183, in client.connect(MQTT_SERVER, MQTT_PORT) File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 912, in connect self.connect_async(host, port, keepalive, File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 979, in connect_async if port <= 0: TypeError: '<=' not supported between instances of 'str' and 'int' 2023-01-30 02:30:11,939 INFO Connected to device:/dev/ttyACM0 Traceback (most recent call last): File "/usr/src/app/rflink2mqtt.py", line 183, in client.connect(MQTT_SERVER, MQTT_PORT) File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 912, in connect self.connect_async(host, port, keepalive, File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 979, in connect_async if port <= 0: TypeError: '<=' not supported between instances of 'str' and 'int'
> 
> Did I something wrong or there is another issue ? Sorry to disturb you with this...

Indentation flew away with copy paste. no error for that in the stack

**Comment by Mickaelh51** [comment]
is it ok for you ?

**Comment by Domos2** [comment]
No it is not working.  my comment for indentation was misunderstood, I just said not to take indentation in account in my post as copy paste was bad; My stack is ok , container start but it gives me the error log in post before. and this error repeat itself endlessly...

**Comment by Domos2** [comment]
Any idea for your new script and the error I got ?

**Comment by Mickaelh51** [comment]
Hi @Domos2 
I tested with new directory test into this repo and all work for me.
can you test and close this issue if it's ok for you

++

**Comment by Domos2** [comment]
Yeah ! all seems to work ! you rock ! Thanks a lot !
